### ISSUE TITLE
weird zooming behavior

### ISSUE THREAD

**Issue by haehn** [michaschwab/easypz#1]
great stuff but this bugs me:

zoom in

move mouse

zoom out

--> weird jumpy behavior, does not feel natural

**Comment by michaschwab** [comment]
Thanks for letting me know!

Does this happen on multiple visualizations, or just one? Where did you see this?
What do you mean by jumpy? Is the problem that it doesn't keep the visualization centered around the pointer when you zoom out? If so, this could be because EasyPZ tries to keep the visualization visible (so people don't get lost) by using a bounding max within which the visualization has to live, which feels a bit odd sometimes when zooming out. You can disable this: https://github.com/michaschwab/easypz/wiki#scale-and-translate-bounds

Is that it?

**Comment by michaschwab** [comment]
I'll close this since I'm not sure what you mean, @haehn! Feel free to ping me if you can provide more explanation, thanks!
